apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-chatbot-cache
  namespace: kubernetes-namespace-template
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-gp3
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-chatbot-cache-dev
  namespace: kubernetes-namespace-template
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-gp3
  resources:
    requests:
      storage: 3Gi