apiVersion: batch/v1
kind: CronJob
metadata:
  name: sharepoint-scrape-cron
  namespace: kubernetes-namespace-template
  labels:
    app: sharepoint-scrape
    version: v${Build.BuildNumber}
    environment: test
    owner: owner-template
spec:
  concurrencyPolicy: Forbid
  schedule: "30 1 * * 6" # Every very Saturday at 1:30 AM
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30
      template:
        metadata:
          labels:
            app: sharepoint-scrape
            version: v${Build.BuildNumber}
            environment: test
            owner: owner-template
        spec:
          containers:
            - name: scrape
              image: 674877602397.dkr.ecr.eu-central-1.amazonaws.com/ai-chatbot-sharepoint-scrape:${Build.BuildNumber}
              volumeMounts:
                - name: shared-data
                  mountPath: "/data"
              env:
                - name: GRAPH_URI
                  value: https://graph.microsoft.com
                - name: TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: ai-chatbot-ingestion
                      key: tenant_id
                - name: AUTHORITY
                  valueFrom:
                    secretKeyRef:
                      name: ai-chatbot-ingestion
                      key: authority
                - name: CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: ai-chatbot-ingestion
                      key: client_id
                - name: SCOPE
                  valueFrom:
                    secretKeyRef:
                      name: ai-chatbot-ingestion
                      key: scope
                - name: THUMBPRINT
                  valueFrom:
                    secretKeyRef:
                      name: ai-chatbot-ingestion
                      key: thumbprint
                - name: CERT_FILE_BASE64
                  valueFrom:
                    secretKeyRef:
                      name: ai-chatbot-ingestion
                      key: cert_file_base64
                - name: SCRAPE_FOLDER_PATH
                  value: "/data/sharepoint"
                - name: MONGO_INITDB_ROOT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ai-chatbot-ingestion
                      key: mongo_initdb_root_username
                - name: MONGO_INITDB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ai-chatbot-ingestion
                      key: mongo_initdb_root_password
                - name: MONGO_HOST
                  valueFrom:
                    secretKeyRef:
                      name: ai-chatbot-ingestion
                      key: mongo_host
                - name: MONGO_PORT
                  valueFrom:
                    secretKeyRef:
                      name: ai-chatbot-ingestion
                      key: mongo_port
                - name: MONGO_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: ai-chatbot-ingestion
                      key: mongo_db_name
                - name: MONGO_DOCUMENTS_COLLECTION_NAME
                  valueFrom:
                    secretKeyRef:
                      name: ai-chatbot-ingestion
                      key: mongo_documents_collection_name
                - name: MONGO_PAGES_COLLECTION_NAME
                  valueFrom:
                    secretKeyRef:
                      name: ai-chatbot-ingestion
                      key: mongo_pages_collection_name
                - name: ORGANIZATION_NAME
                  value: "TEMPLATE"
          restartPolicy: OnFailure
          volumes:
            - name: shared-data
              persistentVolumeClaim:
                claimName: shared-data-pvc